name: Debug CI Variables

on: 
  push:
    branches:
      - main
      - develop
  pull_request_target:
    branches:
      - main
      - develop

jobs:
  debug-variables:
    name: Debug variables
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "testing!!"