name: Debug CI Variables

# Run this workflow only when called by other workflows
on:
  workflow_call:

jobs:
  debug-variables:
    name: Debug variables
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "GitHub event name: ${{ github.event_name }}"
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub head ref: ${{ github.head_ref }}"
          echo "GitHub base ref: ${{ github.base_ref }}"
      