# Run this workflow only on pushes to main
on:
  push:
    branches:
      - main

jobs:
  debug_ci:
    uses: ./.github/workflows/debug_variables.yml

  lint:
    uses: ./.github/workflows/lint_and_format.yml
    
  deploy_astro_site:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/astro_pages.yml
