# Run this workflow only on pushes to main
on:
  push:
    branches:
      - main

jobs:
  debug_ci:
    name: Debug CI Variables
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/debug-variables.yml
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/eslint.yml
  deploy_astro_site:
    name: Deploy Astro site
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/astro-pages.yml
