name: Pull Request Checks

# Run this workflow on all PRs
on:
  pull_request:
    branches:
      - '*'

jobs:
  debug_ci:
    name: Debug CI Variables
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Debug variables
        uses: ./.github/workflows/debug-variables.yml
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ESLint
        uses: ./.github/workflows/eslint.yml
