name: Pull Request Checks

# Run this workflow on all PRs
on:
  pull_request:
    branches:
      - '*'

jobs:
  debug_ci:
    uses: ./.github/workflows/debug_variables.yml

  lint:
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/eslint.yml
