name: Pull Request Checks

# Run this workflow on all PRs
on:
  pull_request:
    branches:
      - '*'

jobs:
  debug_ci:
    uses: ./.github/workflows/debug-variables.yml
  lint:
    uses: ./.github/workflows/eslint.yml
